FORMAT: 1A
HOST: http://www.google.com

# Interface of cdm project v1

    本API文档包含了所有接口   版本号为`v1`
    
    注:所有请求均以`POST`方式提交
    
    URL地址  http://<domain>/php/<action>
    
    

# 分组详细接口信息

# Group User用户信息

### User对象属性
    id - 用户的唯一ID
    user - 用户的昵称
    email - 用户的注册邮箱
    date - 用户的注册日期与时间
    
    

## Notes Collection [/notes]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
